[package]
name = "muzero-mcts"
version.workspace = true
edition.workspace = true

[dependencies]
muzero-core = { path = "../core" }
rand = "0.8"
rand_chacha = "0.3"
rand_distr = "0.4"

[dev-dependencies]
proptest = "1"
